name: Creating VPC using module from PVT repo

on:
#  workflow_dispatch
  push:
    branches:
      - Master

jobs:
  terraform-module-pvt-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1
      - name: Set up Git credentials
        run: |
          git config --global user.name "narendraba"
          git config --global user.email "ballipallinarendra@gmail.com"
          git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Terraform Init
        working-directory: ./modules
        run: terraform init

      - name: Terraform Plan
        working-directory: ./modules
        run: terraform plan

      - name: Terraform Apply
        #if: github.ref == 'refs/heads/main'
        working-directory: ./modules
        run: terraform apply -auto-approve

  
