name: 'Infra Deletion for private module repo'

on:
  workflow_dispatch # Manually trigger the destroy workflow

jobs:
  private-module-repo-destroy:
    name: 'Destroy Infrastructure'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.6'

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: 'Terraform Init'
        working-directory: ./modules/VPC-module
        run: terraform init
        
      - name: 'Terraform plan'
        working-directory: ./modules/VPC-module
        run: terraform plan

      - name: 'Terraform Destroy'
        working-directory: ./modules/VPC-module
        run: terraform destroy -auto-approve
